primary_region = 'fra'
kill_signal    = "SIGINT"
kill_timeout   = 5

[env]
	APP_DEPLOYMENT_ENV  = "staging"

[deploy]
	strategy = "rolling"

[[services]]
	protocol             = "tcp"
	auto_stop_machines   = "suspend"
	auto_start_machines  = true
	min_machines_running = 0
	processes            = ['app']

	[services.concurrency]
		hard_limit = 100
		soft_limit = 50
		type       = "requests"

	[[services.ports]]
		handlers = ["tls", "http"]
		port     = 443

	[[services.tcp_checks]]
		grace_period  = "1s"
		interval      = "15s"
		restart_limit = 0
		timeout       = "2s"

[[vm]]
	size      = "shared-cpu-1x"
	memory    = "512mb"
	processes = ["app"]
