name: 🧹 Destroy PR Preview

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  pull_request:
    types: [closed]

jobs:
  destroy-pr-preview:
    name: "Destroying preview deployment for PR#${{ github.event.number }}"
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl apps destroy "f42-memory-game-pr-${{ github.event.number }}" --yes || true
