name: 🚀 Validation Pipeline
concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  actions: write
  contents: read
  # Required to put a comment into the pull-request
  pull-requests: write
jobs:
  lint:
    name: ⬣ Biome lint
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - uses: biomejs/setup-biome@v2
     - run: biome ci . --reporter=github

  typecheck:
    needs: lint
    name: 🔎 Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"
      - run: pnpm install --prefer-offline --frozen-lockfile
      # - run: pnpm run typecheck
      - run: |
          echo "Type check: ✅ (but disabled)"

  vitest:
    needs: typecheck
    name: ⚡ Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"
      - run: pnpm install --prefer-offline --frozen-lockfile
      - run: pnpm run test:cov
      - name: "Report Coverage"
        # Only works if you set `reportOnFailure: true` in your vite config as specified above
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2


  deploy-preview:
    name: "🚀 Deploy Preview"
    needs: [lint, typecheck, vitest]
    uses: forge42dev/workflows/.github/workflows/deploy-to-fly.yaml@monorepo-matrix
    with:
      github_environment: "pr-preview"
    secrets:
      fly_api_token: ${{ secrets.FLY_API_TOKEN }}
      fly_secrets: |
        SUPABASE_URL=${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
        DATABASE_URL=${{ secrets.DATABASE_URL }}
        DIRECT_URL=${{ secrets.DIRECT_URL }}
        SESSION_SECRET=${{ secrets.SESSION_SECRET }}
